version: "3.8"

services:
  discovery:
    build:
      context: ./discovery
    container_name: discovery-service
    ports:
      - "8081:8081"
    networks:
      - app-network
    restart: always

  gateway:
    build:
      context: ./gateway
    container_name: gateway-service
    ports:
      - "8080:8080"
    depends_on:
      - discovery
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery:8081/eureka/
    networks:
      - app-network
    restart: always

  rabbitmq:
    image: "rabbitmq:3.12-management"
    container_name: rabbitmq
    ports:
      - "9000:5672"
      - "9001:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "admin"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
